#ifndef LILYGO_CM0_APPKIT_LV_CONF_H
#define LILYGO_CM0_APPKIT_LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 32
#define LV_MEM_SIZE (8U * 1024U * 1024U)

#ifndef LILYGO_UI_USE_OPENGLES
#define LILYGO_UI_USE_OPENGLES 0
#endif
#ifndef LILYGO_UI_USE_NANOVG
#define LILYGO_UI_USE_NANOVG 0
#endif
#if LILYGO_UI_USE_OPENGLES && LILYGO_UI_USE_NANOVG
#error "Select only one GPU draw unit"
#endif
#define LV_USE_OPENGLES (LILYGO_UI_USE_OPENGLES || LILYGO_UI_USE_NANOVG)
#define LV_USE_DRAW_OPENGLES LILYGO_UI_USE_OPENGLES
#define LV_USE_DRAW_NANOVG LILYGO_UI_USE_NANOVG
#define LV_USE_NANOVG LILYGO_UI_USE_NANOVG
#define LV_NANOVG_BACKEND LV_NANOVG_BACKEND_GLES2
#define LV_USE_MATRIX LV_USE_OPENGLES
#define LV_USE_FLOAT LV_USE_OPENGLES
#define LV_USE_DRAW_SW 1
#define LV_USE_OPENGLES_DEBUG 0

#if defined(CM0_APP_SIMULATOR) || defined(LAUNCHER_SIMULATOR)
#define LV_USE_SDL 1
#define LV_SDL_DIRECT_EXIT 0
#define LV_SDL_FULLSCREEN 0
#define LV_USE_LINUX_FBDEV 0
#define LV_USE_LINUX_DRM 0
#define LV_USE_EVDEV 0
#else
#define LV_USE_SDL 0
#define LV_USE_LINUX_FBDEV 1
#define LV_USE_LINUX_DRM 1
#define LV_USE_LINUX_DRM_GBM_BUFFERS 0
#define LV_USE_EVDEV 1
#endif

#define LV_USE_WAYLAND 0

#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_USE_OBJ_NAME 1
#define LV_USE_TRANSLATION 1

#define LV_USE_FS_STDIO 1
#define LV_FS_STDIO_LETTER 'A'
#define LV_FS_DEFAULT_DRIVER_LETTER 'A'
#define LV_USE_LODEPNG 1

#define LV_FONT_MONTSERRAT_14 0
#define LV_FONT_MONTSERRAT_22 0
#define LV_FONT_MONTSERRAT_28 0
#define LV_FONT_MONTSERRAT_36 0
#define LV_FONT_MONTSERRAT_48 0
#define LV_USE_FREETYPE 1
#define LV_FREETYPE_USE_LVGL_PORT 0
#define LV_FREETYPE_CACHE_FT_GLYPH_CNT 256
#define LV_FONT_CUSTOM_DECLARE                                                \
  const lv_font_t *lilygo_ui_font_get(uint32_t size);                        \
  void lilygo_ui_fonts_deinit(void);
#define LV_FONT_DEFAULT lilygo_ui_font_get(14)

#endif
